### ISSUE TITLE
Wither is able to dig through stacked dimension portal blocks with Charge attack

### ISSUE THREAD

**Issue by NighthowlerStudios** [Insane96/ProgressiveBosses#106]
**Describe the bug**
title is self explanatory

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.8
 - Progressive Bosses: 3.4.0 Alpha
 - InsaneLib: 1.3.2

**Expected behavior**
don't please.  this makes it impossible to kill it.  please add a block blacklist as well so I can make sure vertical dimension stack library blocks aren't being affected as well.

**Can the issue be reproduced with a mininal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)**
Yes

**Comment by Insane96** [comment]
> don't please. this makes it impossible to kill it.

Why it's impossible to kill?

**Comment by Insane96** [comment]
Also can't reproduce with the default config

**Comment by NighthowlerStudios** [comment]
> > don't please. this makes it impossible to kill it.
> 
> Why it's impossible to kill?

it is impossible to kill because it drifts around distantly in the void, which unrenders its model so you never know where it is.  Then it will proceed to charge you again but then just return to the void, over and over.  

in the overworld, if it enters the void under the bedrock layer, you cannot go in after it as you will obviously instantly fall until death with nothing stopping you

**Comment by NighthowlerStudios** [comment]
> Also can't reproduce with the default config

![image](https://user-images.githubusercontent.com/82226641/141658156-9ff789fe-77fa-4203-8cd9-e4690b29ae2b.png)
so...:/ this is what mine has already.

**Comment by NighthowlerStudios** [comment]
if you want I can send you my entire config file if you need to check for some sort of syntax thing.  but for my pack?  it's breaking bedrock layer somehow.  again I'm gonna check if it's breaking vertical dimension stack blocks which only the player should be able to break.

**Comment by NighthowlerStudios** [comment]
you might be able to reproduce it using Kaleidio's Battle Pack 3.7.3 which is available on CurseForge.  that's what I'm using right now for testing

**Comment by Insane96** [comment]
Send it

Il Sab 13 Nov 2021, 21:32 Kaleidio ***@***.***> ha scritto:

**Comment by NighthowlerStudios** [comment]
alright, I have a feeling something might be out of order since I let the mod's updates append the config ^^'

https://pastebin.com/Bjw1m7dA

**Comment by NighthowlerStudios** [comment]
did further testing.  it is indeed vanilla dimension stack blocks which are supposed to act as bedrock but just get broken by its charge anyway

the block is provided by the Deep Dark Dimension mod and looks like this:
![2021-11-13_20 42 05](https://user-images.githubusercontent.com/82226641/141658526-e16492d8-c399-4d02-93a8-b2ad40afa5ac.jpg)

**Comment by NighthowlerStudios** [comment]
can you add a blacklist for what blocks the wither should not be able to destroy so I can fix my pack, please?

**Comment by Insane96** [comment]
Then you need to fix it yourself with block tags

**Comment by Insane96** [comment]
> you might be able to reproduce it using Kaleidio's Battle Pack 3.7.3 which is available on CurseForge. that's what I'm using right now for testing

So you lied on the "Can the issue be reproduced with a mininal set of mods?" question

**Comment by NighthowlerStudios** [comment]
> > you might be able to reproduce it using Kaleidio's Battle Pack 3.7.3 which is available on CurseForge. that's what I'm using right now for testing
> 
> So you lied on the "Can the issue be reproduced with a mininal set of mods?" question

sorry man, I didn't lie, I didn't investigate hard enough

**Comment by NighthowlerStudios** [comment]
okay I can see you're mad, but this definitely needs a blacklist added because certain blocks that act as bedrock but are added by mods are being deleted...

**Comment by NighthowlerStudios** [comment]
> > you might be able to reproduce it using Kaleidio's Battle Pack 3.7.3 which is available on CurseForge. that's what I'm using right now for testing
> 
> So you lied on the "Can the issue be reproduced with a mininal set of mods?" question

you only need one other mod to cause the issue.  Deep in the Caves - Warden Dimension Mod
