### ISSUE TITLE
3.4.1-mc1.16.5 - Crash to Desktop/Launcher

### ISSUE THREAD

**Issue by HalestormXV** [Insane96/ProgressiveBosses#108]
Progressive Bosses 3.4.1-mc1.16.5
Modpack: Mineshaft and Monsters
Crash Report: https://pastebin.com/puzvTBii
Description: The crash seems fairly random however if I am reading the stack trace correctly perhaps there is some issue with certain mobs that might be added with other mods? This particular crash above occured when a mimic decided to attack.

**Comment by Insane96** [comment]
I can't test this with a modpack, I need fewer mods and seems Infernal Expansion might be the cause

**Comment by Insane96** [comment]
No follow up so going to close the issue
