### ISSUE TITLE
Can't place wither skulls in the nether

### ISSUE THREAD

**Issue by YeetmeJesus** [Insane96/ProgressiveBosses#117]
**Describe the bug**
The Wither will not spawn in the nether with the nether only option

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 1.16.5
 - Progressive Bosses: 
 - InsaneLib: 

**Steps to reproduce**
1. 
2. 
3. 

**Expected behavior**
Spawn the wither

**Screenshots**

**Logs**
Use a paste site (pastebin, gist) to send the game logs (both logs and crash if applicable)

**Can the issue be reproduced with a mininal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)**
Yes/No
[progressivebosses-common.txt](https://github.com/Insane96/ProgressiveBosses/files/7931056/progressivebosses-common.1.txt)

**Comment by Insane96** [comment]
Fixed in 3.4.3
