### ISSUE TITLE
[1.18.1] Crashing Ticking Entity - Ender Dragon

### ISSUE THREAD

**Issue by itsdinkd** [Insane96/ProgressiveBosses#118]
Seems to be issue with Latest InsaneLib and Progressive Bosses (does not crash on insane lib 1.4.2) 

https://gist.github.com/CornOnTheCaleb/5b7e24d3a08338c09ccacc14826744de

As shown in the latest.log above, when the player encountered ender dragon, they crashed and are stuck in a crash loop. 

Ticket on insanelib: https://github.com/Insane96/InsaneLib/issues/11

**Comment by Insane96** [comment]
Please follow the issue template.
