### ISSUE TITLE
Crash when going to the end

### ISSUE THREAD

**Issue by SirEndii** [Insane96/ProgressiveBosses#119]
**Describe the bug**
When we go to the end, the server crashes. We already killed the dragon and explored the end.

**Versions:**
 - Minecraft: 1.18.1
 - Forge: 39.0.76
 - Progressive Bosses: 3.5.0
 - InsaneLib: 1.4.3

**Steps to reproduce**
We already killed the dragon one time and built something in the end.
But some time later, the server crashes when we try to go again to the end.

**Expected behavior**
No crash 

**Logs**
Crash stacktrace + some extras; https://gist.github.com/Seniorendi/b259fffa1b47ff50c0fcfa4854faba83

**Can the issue be reproduced with a mininal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)**
Didn't test, don't really have the time.
I'll test it when I get the time.

**Comment by Insane96** [comment]
Downgrade InsaneLib to 1.4.2

**Comment by SirEndii** [comment]
kay
