### ISSUE TITLE
Progressive Bosses v3.5.7 tagged as compatible with 1.18.1 AND 1.18.2 on curseforge

### ISSUE THREAD

**Issue by Haloghen** [Insane96/ProgressiveBosses#122]
**Describe the bug**
Progressive Bosses v3.5.7 tagged as compatible with 1.18.1 AND 1.18.2 on curseforge, should be tagged as 1.18.2 only since it crashes on startup on 1.18.1.

**Versions:**
 - Minecraft: 1.18.1
 - Forge: 39.1.2
 - Progressive Bosses: 3.5.7
 - InsaneLib: 1.4.3

**Steps to reproduce**
1. Install Mod
2. Open Minecraft

**Expected behavior**
Minecraft Starts as normal.

**Logs**
https://nekobin.com/bekilelume

**Can the issue be reproduced with a mininal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)**
Yes

**Comment by Insane96** [comment]
Fixed
