### ISSUE TITLE
Lag spike on server due to Elder Guardian

### ISSUE THREAD

**Issue by Krampus69** [Insane96/ProgressiveBosses#123]
Hello hello 👋 

**Describe the bug**
I encounter lag spikes coming from Progressive Bosses on my modpack, I used spark to detect the lag spike and it says that it has something to do with the elder guardian.

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.34
 - Progressive Bosses: ProgressiveBosses-3.4.3-mc1.16.5
 - InsaneLib: InsaneLib-1.4.2-mc1.16.5

**Steps to reproduce**
1. Fly fast on a heavy modded server
2. Use spark to find out the lag spike
(I wouldn't recommend doing all this tbh, I'm just here to talk, maybe you'll have an idea if that ever happened with someone else here...)

**Expected behavior**
No lag spike ? :D

**Screenshots**

Here is the spark link explaining the lag spike : https://spark.lucko.me/5x7jyKXlMz

**Logs**

[latest.log](https://github.com/Insane96/ProgressiveBosses/files/8502908/latest.log)

**Can the issue be reproduced with a mininal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)**

Probably not

Thank you for your mod also, I'm really enjoying it. If you have any idea on why this would happen, that would help me a lot. Thanks again :)

**Comment by Insane96** [comment]
That's pretty strange. I even check for nearby Ender Guardians every 20 ticks instead of every tick

**Comment by Insane96** [comment]
The spark link has expired and got no other people with same problem. Just reopen the issue if still persists
