### ISSUE TITLE
Add config option to prevent the Wither from being spawned in a way that would collide with bedrock.

### ISSUE THREAD

**Issue by James103** [Insane96/ProgressiveBosses#128]
Currently (in vanilla Minecraft), the Wither can be spawned in such a way so as to collide with Bedrock. If Obsidian is placed below the Wither, this can trap the Wither, effectively locking it in place for (possibly the full duration of) the fight.

I would like to suggest adding in a config option to prevent the Wither from being spawned in such a way so as to collide with bedrock. If it is enabled, when a player attempts to spawn a Wither, a 3x6x3 area centered on the hitbox of the to-be-spawned Wither spanning from 1 block below its bottom to 1 block above its top is checked for any blocks (including bedrock) that can't be broken by a Wither. If such blocks are detected, the Wither fails to spawn and a message is sent to the player.

A variant of this was originally proposed in https://github.com/orlouge/no-mob-farms/issues/5 on the Fabric side, but the developer of that mod rejected some of the ideas originally proposed. I feel like should be a good compromise.

NOTE: This is separate from https://github.com/Insane96/ProgressiveBosses/issues/98, which proposes a config option that lets the Wither destroy blocks that are normally unbreakable by Withers, but unbreakable blocks remain unbreakable. That option is effective at runtime, while this proposal is effective at spawning.

**Comment by Insane96** [comment]
The wither already breaks blocks below him so it doesn't stay stuck. Makes no sense stopping the wither from spawning if still at first damage he takes he gets unstuck.

If that doesn't work, well, the this becomes a bug and not a feature request.
