### ISSUE TITLE
Wither boss can destroy bedrock

### ISSUE THREAD

**Issue by Butamichi** [Insane96/ProgressiveBosses#132]
**Describe the bug**
During the fight with one Wither Boss I used the common tactic of spawning him under the end portal to the overworld, mid fight when he makes a hude explosion and summon minions he deleted the End portal blocks and bedrock.

**Versions:**
 - Minecraft: 1.18.2
 - Forge: Fabric
 - Progressive Bosses: 1.0.6
 - InsaneLib: 

**Steps to reproduce**
1. Summon the boss
2. DPS him until he does that atack
3. Say goodbay to any block near him including bedrock

**Expected behavior**
Not breaking Bedrock with the risk of falling to the void on the overworld or  being able to bug me on the nether roof on a server
**Screenshots**
![image](https://user-images.githubusercontent.com/106127703/174849497-2a93ba08-4b2f-40a7-aa46-857090230d4d.png)

**Logs**
No crash so no logs

**Can the issue be reproduced with a mininal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)**
IDK

**Comment by Insane96** [comment]
This is not the Fabric version of the mod
