### ISSUE TITLE
1.12.2 Custom Rewards Broken

### ISSUE THREAD

**Issue by 233Neon** [Insane96/ProgressiveBosses#133]
1.12.2 Custom Rewards are Broken, please fix this! I know you probably aren't planning on any future updates, but a quick bug fix would be highly appreciated for modpack creators!

**Comment by Insane96** [comment]
"A quick bug fix update". What makes you think that? 1.12 had just the config option, the reward system was not implemented.

**If** I'm going to update, I will remove the option as it's not broken, it's not implemented at all.
