### ISSUE TITLE
[Bug] Wither "Explosion" dupes items

### ISSUE THREAD

**Issue by TheonlyTazz** [Insane96/ProgressiveBosses#135]
**Describe the bug**
When getting the Wither to low(er) health, the size increase and following explosion causes items to be duped

**Versions:**
 - Minecraft: 1.18.2
 - Forge: 40.1.54
 - Progressive Bosses: ProgressiveBosses-3.5.15-mc1.18.2.jar
 - InsaneLib: InsaneLib-1.5.1-mc1.18.2.jar

**Steps to reproduce**
1. Build a wither cage
2. bring it to low health
3. place down blocks
4. wait for it to turn blue and trigger explosion
5. explosion breaks blocks and 1 sec later, they get spawned in again, 

**Expected behavior**
blocks break, dont get duped

**Screenshots**
![image](https://user-images.githubusercontent.com/3908847/177329527-2d980da3-7dfa-4be7-b369-28a32a0e5d7f.png)
![image](https://cdn.discordapp.com/attachments/123194979509207040/993858860991389756/vlc_IgLw4AYsfO.gif)
https://cdn.discordapp.com/attachments/123194979509207040/993858860991389756/vlc_IgLw4AYsfO.gif
**Can the issue be reproduced with a mininal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)**
pressumably

**Additional Notes**
This Issue has been reported on the FTB Modpack Issue Tracker, linking here for better tracking
[FTB Modpack Issue Tracker](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1064)

**Comment by Insane96** [comment]
> Can the issue be reproduced with a mininal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)
> pressumably

Presumably is not a valid response. You must test it with a minimal set of mods

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/177412436-121523ee-f6f7-494a-a900-18059f19ea78.png)
![image](https://user-images.githubusercontent.com/3908847/177412631-fd6dd7e1-7a74-4596-bbb6-8466cc8f5f4e.png)

Issue also appears on an Instance with only Progressive Bosses installed 
![image](https://user-images.githubusercontent.com/3908847/177412512-d1943f3f-5d20-4174-9ad4-d2fe497e4fef.png)

**Comment by TheonlyTazz** [comment]
![img](https://i.imgur.com/rYS5uqO.gif)

just to show you, this actually is happening right after the blue 'explosion'

**Comment by Insane96** [comment]
Fixed in 3.5.16
