### ISSUE TITLE
Incompatibility with Ars Magica: Legacy

### ISSUE THREAD

**Issue by IchHabeHunger54** [Insane96/ProgressiveBosses#136]
## Versions
 - Minecraft: 1.18.2
 - Forge: 40.1.48
 - Progressive Bosses: 3.5.11
 - InsaneLib: 1.5.0

## Describe the bug
Hello. I am one of the devs of Ars Magica: Legacy, and we recently received an incompatibility report for Progressive Bosses (original issue: https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/issues/309 ). The problem is that apparently, the boss bars do not properly disappear when this mod is installed, but do without it.

I have not yet verified the bug myself, but I had a discussion on Discord with the original report's author, who specifically removed your mod to solve the issue.

Being the dev, I wanted to ask if this is a problem on our end or on yours, since I do not know how your stuff works internally. If you need a look at our bossbar management, here you go: https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/blob/version/1.18.x/src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/entity/AbstractBoss.java
If you have further questions, feel free to reach out to me here or on Discord.

## Logs
N/A

## Tried reproducing with just Progressive Bosses?
As described, not using Progressive Bosses solves the issue.

**Comment by Insane96** [comment]
Could you reproduce it with the latest Forge, Progressive Bosses and InsaneLib version?

**Comment by IchHabeHunger54** [comment]
Mods used for testing:

Forge 40.1.54
InsaneLib 1.5.1
Progressive Bosses 3.5.16
Ars Magica: Legacy 1.1.0
Patchouli 71.1
JEI 9.7.0.209
Curios 5.0.7.1

After some testing, I am unable to get any bossbars both with and without your mod. However, the bossbars show up in my dev environment, so it is likely that this is a problem on our end. I will contact the original issue's author for any additional insights, and leave this issue open until the problem is finally resolved.

**Comment by Insane96** [comment]
Actually I don't touch boss bars in anyway (I did in 1.12), so don't think it's an issue on my end. Gonna leave this open for the time begin

**Comment by Insane96** [comment]
No updates in a while. Closing
