### ISSUE TITLE
Enchanting level problem

### ISSUE THREAD

**Issue by 48004800** [Insane96/ProgressiveBosses#141]
## Versions
 - Minecraft: 1.19.2
 - Forge: 43.1.47
 - Progressive Bosses: 3.7.3
 - InsaneLib: 1.7.1

The equipment enchanting level of the wither minions will change to 0 when it is set to a high level(no more than 255)

**Comment by 48004800** [comment]
According to the test, the maximum enchanting level is 127

**Comment by Insane96** [comment]
That's strange. Gonna test that

**Comment by Insane96** [comment]
Tested with this and didn't reset on game load

```			
[Wither.Minions.Equipment.Enchantments]
	#Chance (at max difficulty) for the Wither Minion's Sword to be enchanted with Sharpness. Note that every 100% chance adds one guaranteed level of the enchantment, while the remaining dictates the chance to add on more level.
	#Range: 0.0 ~ 255.0
	"Sharpness Chance" = 200
	#Chance (at max difficulty) for the Wither Minion's Sword to be enchanted with Knockback. Note that every 100% chance adds one guaranteed level of the enchantment, while the remaining dictates the chance to add on more level.
	#Range: 0.0 ~ 255.0
	"Knockback Chance" = 100
	#Chance (at max difficulty) for the Wither Minion's Bow to be enchanted with Power. Note that every 100% chance adds one guaranteed level of the enchantment, while the remaining dictates the chance to add on more level.
	#Range: 0.0 ~ 255.0
	"Power Chance" = 200
	#Chance (at max difficulty) for the Wither Minion's Bow to be enchanted with Punch. Note that every 100% chance adds one guaranteed level of the enchantment, while the remaining dictates the chance to add on more level.
	#Range: 0.0 ~ 255.0
	"Punch Chance" = 215
```

**Comment by 48004800** [comment]
<img width="1223" alt="屏幕截图 2022-11-09 100832" src="https://user-images.githubusercontent.com/78255094/200719901-d00023fd-977f-4008-954f-b393e3653b1a.png">

**Comment by 48004800** [comment]
![2022-11-09_10 10 18](https://user-images.githubusercontent.com/78255094/200720021-0d6feb66-8e1f-469a-b141-e22cee5fdaf6.png)

**Comment by 48004800** [comment]
![2022-11-09_10 10 11](https://user-images.githubusercontent.com/78255094/200720058-662bc155-2a06-472b-a8ac-6a4b8cb4591e.png)

**Comment by Insane96** [comment]
Oh the config works properly then, it's in-game that the enchantments are set to 0. I'll investigate

**Comment by Insane96** [comment]
This seems to be intended as enchantments can't go over 127. Next update will cap the config to 127 instead of 255
