### ISSUE TITLE
Ender dragon has no trophies

### ISSUE THREAD

**Issue by 48004800** [Insane96/ProgressiveBosses#143]
## Versions
 - Minecraft: 1.19.2
 - Forge: 43.1.52
 - Progressive Bosses: 3.7.4
 - InsaneLib: 1.7.2
No interference from other MODs

Ender dragon has no loot. I have enabled loot table insertion in settings
After I modified the loot table of ender dragon, there is still no loot
In the same loot table, the death of the wither will produce loots, but the death of the ender dragon will not

**Comment by Insane96** [comment]
The Dragon has only a chance to drop a GApple, so check if that's actually the case

**Comment by 48004800** [comment]
> The Dragon has only a chance to drop a GApple, so check if that's actually the case
I tried many times, but golden apple never appeared

I manually modified its loot, but it still has no loot
Ender dragon doesn't seem to have loot

**Comment by Insane96** [comment]
What do you mean you modified manually the loot? You changed the loot via datapack?

**Comment by 48004800** [comment]
<img width="129" alt="image" src="https://user-images.githubusercontent.com/78255094/203058827-a5fa3403-8791-4596-8ffa-f037b144a723.png">
I found that even if the probability in the loot table of the ender dragon is changed to 100%, there is still no loot

**Comment by 48004800** [comment]
I copied the contents of the wither json file to the ender dragon, but there is still no loot. But Wither works normally

**Comment by Insane96** [comment]
I need the datapack

**Comment by 48004800** [comment]
I didn't use datapack. I do this by modifying the json file in the jar file

[entity.zip](https://github.com/Insane96/ProgressiveBosses/files/10072397/entity.zip)

**Comment by Insane96** [comment]
You should never do that
Use datapacks, they exist for a reason

**Comment by 48004800** [comment]
I do this because I don't know how to use packets.
 The key point of this issue is that the loot of the end dragon does not exist
I hope you check that's all.

**Comment by 48004800** [comment]
I just suspect that the loot of the ender dragon was not inserted successfully
There has never been an enchanted gold apple (no interference from other MODs)

**Comment by 48004800** [comment]
The problem does not exist. When the health value of the ender dragon is 0, the golden apple will fall immediately, and it will really die near the portal

**Comment by 48004800** [comment]
> You should never do that Use datapacks, they exist for a reason
I modify the JAR because I don't know how to use the data package
I will use the data package

**Comment by Insane96** [comment]
Do it via datapack, check if it works. If it doesn't sent it here so I'll check it out.

**Comment by 48004800** [comment]
> Do it via datapack, check if it works. If it doesn't sent it here so I'll check it out.

The problem does not actually exist. 

I always thought that falling objects would fall with xp 
The Ender dragon will drop the loot when the HP is 0, rather than after the body emits purple light.
