### ISSUE TITLE
Elder Guardian eventually becomes completely invulnerable

### ISSUE THREAD

**Issue by HueboWasTaken** [Insane96/ProgressiveBosses#148]
## Versions
 - Minecraft: 1.19.2
 - Forge: 43.2.14
 - Progressive Bosses: 3.7.5
 - InsaneLib: 1.7.5

## Describe the bug
I got an elder guardian spawn egg through apotheosis' capturing enchantment, which I then used to change a vanilla mob spawner into an elder guardian spawner (another apotheosis feature). I used the spawner to farm elder guardians, they started taking less and less damage after each kill until they were completely invulnerable to any damage (even /kill). I suspect this is caused by the 30% resistance given to elder guardians when another guardian in the monument is killed, which is normally not an issue as ocean monuments only have 3 elder guardians. When spawned from a spawner, this resistance stacks infinitely, eventually resulting in an invulnerable mob. If this is the cause then adding a cap to the resistance would fix it.

## Logs
N/A

## Tried reproducing with just Progressive Bosses?
haven't tried with only the relevant mods yet. This happened while playing on a server running the latest version of the M-Tech modpack.

**Comment by Insane96** [comment]
This is due having multiple Elder Guardians in a 64 blocks radius (as the issue says, from a spawner). Prior to MC 1.20.1 disable the Resistances Feature of Elder Guardians. Fixed in 3.9.1
