### ISSUE TITLE
[1.20.1] Crash on load after updating 

### ISSUE THREAD

**Issue by ProsperCraft** [Insane96/ProgressiveBosses#150]
## Versions
 - Minecraft:  1.20.1
 - Forge:  47.1.3
 - Progressive Bosses: ProgressiveBosses-3.9.1-mc1.20.1.jar
 - InsaneLib: InsaneLib-1.11.1-mc1.20.1.jar

## Describe the bug
After updating it appears the library is no longer compatable.

## Logs
It didn't save a proper crash report, find it at the end of the log.
[Use a paste site (https://gist.github.com, https://paste.gemwire.uk) to send the game logs (both logs and crash if applicable)
](https://gist.githubusercontent.com/ProsperCraft/dbc6a7a5b7593e1323a5d0a46eb39c28/raw/dd6f283235be8b8fbb137deb961204434667d7a5/gistfile1.txt)
## Tried reproducing with just Progressive Bosses?
Please test with Progressive Bosses + InsaneLib only (+ any other mod that might be causing the issue)

**Comment by ProsperCraft** [comment]
Downgrading to InsaneLib-1.10.2-mc1.20.1.jar allows the pack to load.

**Comment by Insane96** [comment]
Fixed in 3.9.2
