### ISSUE TITLE
Ender Dragon doesn't Work

### ISSUE THREAD

**Issue by wabeb325** [Insane96/ProgressiveBosses#151]
- Minecraft: 1.18.2
 - Forge: 40.2.10
 - Progressive Bosses: 3.6.7
 - InsaneLib: 1.5.3

The Ender Dragon doesn't work with Nullscape 1.18, none of its abilities work or are modified. Even if is respawned, it doesn't work either.

Progressive Bosses + InsaneLib + Nullscape (Last Version)

**Comment by Insane96** [comment]
Does it work with max difficulty?

**Comment by wabeb325** [comment]
Yeah, I already tried changing it to the maximum difficulty and even increasing it in the config, and nothing.

**Comment by Insane96** [comment]
Does it work with PB 3.6.6?

**Comment by wabeb325** [comment]
Yeah, it doesn't work either.

**Comment by Insane96** [comment]
Tested with 3.6.7 and Nullscape 1.18.2 ... everything works properly

**Comment by wabeb325** [comment]
Are you sure? I deleted all my external mods to test and verify that it wasn't an external incompatibility, these were the mods I left (InsaneLib is in version 1.5.3)
![image](https://github.com/Insane96/ProgressiveBosses/assets/144356307/413377de-0eda-42be-b191-76671e9442a8)

To be more specific, the other mobs (the Wither and the Elder Guardian) works normally, but the Dragon when entering the end doesn't have any ability applied.

**Comment by Insane96** [comment]
Again, I tested with PB and Nullscape DataPack only.

**Comment by wabeb325** [comment]
Try with the mod version of Nullscape, that's the one with the error

**Comment by Insane96** [comment]
Have you actually tried with PB and Nullscape mod only?

**Comment by Insane96** [comment]
Also `lib_InsaneLib.jar.jar` doesn't sound like a mod downloaded from official sources

**Comment by wabeb325** [comment]
`lib_InsaneLib.jar`, I renamed InsaneLib to make it easier for me to organize, is actually the same mod in the last version 1.5.3.

About testing Nullscape and PB on their own, the same error keeps happening.

**Comment by Insane96** [comment]
Thanks, to make sure it's not the other many mods you had

**Comment by Insane96** [comment]
Did you try with the DataPack?

**Comment by wabeb325** [comment]
Yeah, with the Datapack it works normally, but with the mod not, I think it is because in the Datapack as far as I saw, they didn't changed the main island, while in the mod, yes.

**Comment by Insane96** [comment]
What ... the mod should be just a packaged data pack ...

**Comment by Insane96** [comment]
I have absolutely no clue ... I've tried to test with the mod and the dragon will not even respawn lol.
The mod is broken, not gonna bother more than that, sorry, use the DataPack since should be the same thing
