### ISSUE TITLE
Absorbtion/Additional Health for Elder Guardian doesn't seem to be working?

### ISSUE THREAD

**Issue by aghostofstarman255** [Insane96/ProgressiveBosses#152]
Latest version on everything.
Tested with only Progressive Bosses.

Tested it extensively but maybe I'm missing something?

**Comment by Insane96** [comment]
This hasn't been working since May 2022 lol

**Comment by Insane96** [comment]
Fixed in 3.9.4

**Comment by aghostofstarman255** [comment]
Only commenting on this now to see if this could be possibly fixed in 1.19.2.

**Comment by Insane96** [comment]
Backported this and all the changes from 1.19.4 and 1.20.1 to 1.19.2
