### ISSUE TITLE
[1.20.1 Forge] Enable Attack feature for Elder Guardians can freeze the game permanently 

### ISSUE THREAD

**Issue by TelepathicGrunt** [Insane96/ProgressiveBosses#153]
The issue is most noticeable with Bumblezone on as my Blue Sempiternal Sanctum's Calming Essence event spawns several Guardians and Elder Guardians for players to fight. As player kills the guardians, Progressive Bosses eventually will set getAttackDuration so low that getAttackAnimationScale will be too large and cause an infinite loop in vanilla code
https://github.com/TelepathicGrunt/Bumblezone/issues/303

This is the vanilla code in question. Guardian class. aiStep method.
![image](https://github.com/Insane96/ProgressiveBosses/assets/40846040/6e3c1a37-b547-48da-9e91-0a589ebf8424)
![image](https://github.com/Insane96/ProgressiveBosses/assets/40846040/55191ed8-17c9-4dee-9e3e-6d9604792a07)

This is the mixin at fault (Also fyi, an inject that always cancels is just a silent overwrite that doesn't report conflicts. This is worse than just using an overwrite directly)
https://github.com/Insane96/ProgressiveBosses/blob/4515f4a22f965f25e5bdc4dab88907f347742cca/src/main/java/insane96mcp/progressivebosses/mixin/ElderGuardianMixin.java#L15

https://github.com/Insane96/ProgressiveBosses/blob/4515f4a22f965f25e5bdc4dab88907f347742cca/src/main/java/insane96mcp/progressivebosses/module/elderguardian/feature/AttackFeature.java#L43-L51

I threw in an inject to see what values was coming out of Progressive Bosses. getAttackDuration was being set to 35. Which caused getAttackAnimationScale to be 2.4. And because 2.4 is greater than 1.8, this means j is actually *decreasing* in value which means j can never be greater than h anymore. Thus the infinite loop that freezes the game permanently until restart.
![image](https://github.com/Insane96/ProgressiveBosses/assets/40846040/8f129619-8bfb-477d-a92d-b9432054d948)

In vanilla, getAttackAnimationScale is never greater than 1. This will need to be respected by Progressive Bosses to stop the infinite loop from happening again in the future.

**Comment by Insane96** [comment]
So the problem is basically (other than the inject that always cancel), is that getAttackDuration doesn't return the correct value?

**Comment by TelepathicGrunt** [comment]
Just tested ProgressiveBosses-3.9.5-mc1.20.1.jar with Bumblezone's event and no freeze. Thank you!
