### ISSUE TITLE
wither can be spawned in overworld

### ISSUE THREAD

**Issue by Aceplante** [Insane96/ProgressiveBosses#154]
## Versions
 - Minecraft: 1.20.1
 - Forge: 47.2.19
 - Progressive Bosses: 3.9.5
 - InsaneLib: idk

## Describe the bug
Title. The wither can be spawned in the overworld

**Comment by Insane96** [comment]
That's intended. Also next time report the names. "latest" means nothing

**Comment by Aceplante** [comment]
on your mod page it literally shows you being unable to spawn the wither in the overworld becuase "this dimension cant support it". I thought that was a cool feature. Maybe make it configurable?

also added version

**Comment by Insane96** [comment]
That's for the v4 still in development. It's only available to patreons

**Comment by Aceplante** [comment]
Ah, I did not know, hence the report. Fair enough thank you
