### ISSUE TITLE
Wither sometimes duping Blocks

### ISSUE THREAD

**Issue by xLuPo** [Insane96/ProgressiveBosses#155]
## Versions
 - Minecraft: 1.20.1 
 - Forge: 47.2.8
 - Progressive Bosses: 3.9.5
 - InsaneLib: 1.12.1

## Describe the bug
When the Wither breaks blocks, they sometimes / often get dupe dropped as the Item.

**Comment by Insane96** [comment]
Does it happen with Progressive Bosses only?

**Comment by xLuPo** [comment]
When I played normally in my Modpack it worked fine and after adding Prograssive Bosses, it started happening.

**Comment by Insane96** [comment]
You didn't reply to my question

**Comment by Insane96** [comment]
Closing for no follow up
