### ISSUE TITLE
1.18.2 fabric Lingering Potion doesn't work

### ISSUE THREAD

**Issue by 0-Assassin-0** [Insane96/ProgressiveBosses#157]
## Versions
 - Minecraft: 1.18.2
 - Forge: fabric 0.15.7  fabric_api 0.77.0
 - Progressive Bosses:  ProgressiveBossesFabric-1.18.2-U1
 - InsaneLib:  null

## Describe the bug
only ProgressiveBossesFabric-1.18.2-U1 and fabric installed, all Lingering Potions don't work

## Logs
Use a paste site (https://gist.github.com, https://paste.gemwire.uk) to send the game logs (both logs and crash if applicable)
no crash
## Tried reproducing with just Progressive Bosses?
Please test with Progressive Bosses + InsaneLib only (+ any other mod that might be causing the issue)
fabric with ProgressiveBossesFabric-1.18.2-U1, no need to add insanelib

**Comment by Insane96** [comment]
This mod is Forge only. Ask the fabric porter for bugs
