### ISSUE TITLE
Crashed when shooting End Crystals

### ISSUE THREAD

**Issue by liuseniubi** [Insane96/ProgressiveBosses#163]
## Versions
 - Minecraft: 1.20.1
 - Forge: 47.3.0
 - Progressive Bosses: 3.9.7
 - InsaneLib: 1.15.0

## Describe the bug
Crashed when shooting End Crystals (linked to the Ender Dragon)

## Logs
https://mclo.gs/000sKIz

## Tried reproducing with just Progressive Bosses?
No, but will try it later.

**Comment by Insane96** [comment]
Either downgrade InsaneLib or update PB to v4
