### ISSUE TITLE
Client and Server Crash

### ISSUE THREAD

**Issue by Gryffen1971** [Insane96/ProgressiveBosses#164]
## Versions
 - Minecraft:   1.20.1
 - Forge:   47.3.10
 - Progressive Bosses: 4.2.1
 - InsaneLib:  1.15.0

## Describe the bug
Entered the End and as the Ender Dragon was Appearing the Client and Server Crashed.
Restarted the Server and Client, Rejoined the Server and it crashed again.
Removed Both and Restarted Server and Client. Rejoined Server and was able to Start the Battle and Finish.

Was Unable to Even Attack the Crystals right after loading into The End with those Mods on the Server.

## Logs
Use a paste site (https://gist.github.com, https://paste.gemwire.uk) to send the game logs (both logs and crash if applicable)
Both Files are Attached to this Issue.

## Tried reproducing with just Progressive Bosses? No, Had to Push an Emergency Hotfix for both Client and Server Packages.
I will inform once, I've completed my Hotfix upload.

Please test with Progressive Bosses + InsaneLib only (+ any other mod that might be causing the issue) <---- This will be done after Hotfix is Uploaded and Available to Users.

[latest.log](https://github.com/user-attachments/files/17731680/latest.log)
[crash-2024-11-13_03.34.08-server.txt](https://github.com/user-attachments/files/17731594/crash-2024-11-13_03.34.08-server.txt)

**Comment by Insane96** [comment]
You're using v3 and not v4 as you stated. Update to v4

Il Mer 13 Nov 2024, 12:31 James R Elliott ***@***.***> ha
scritto:

**Comment by Gryffen1971** [comment]
Sorry, had wrong Version.

Updating is "Not Planned" until Mod is out of Beta for Progressive Bosses.
