### ISSUE TITLE
ELDER GUARDIAN CRASH

### ISSUE THREAD

**Issue by Hooligan00** [Insane96/ProgressiveBosses#165]
## Versions
 - Minecraft: 1.20.1
 - Forge: 47.3.11
 - Progressive Bosses: 3.9.7
 - InsaneLib: 1.15.1

## Describe the bug
Crash when I try to damage elder guardian. Please fix, I need sponges.

## Logs
Use a paste site (https://gist.github.com, https://paste.gemwire.uk) to send the game logs (both logs and crash if applicable)

## Tried reproducing with just Progressive Bosses?
Please test with Progressive Bosses + InsaneLib only (+ any other mod that might be causing the issue) 

 its just progressive bosses

[crash-2024-12-09_18.45.37-server.txt](https://github.com/user-attachments/files/18072265/crash-2024-12-09_18.45.37-server.txt)

**Comment by Insane96** [comment]
Update to newer PB, you have a really old version

**Comment by Hooligan00** [comment]
What is a PB?

**Comment by Insane96** [comment]
Progressive Bosses

**Comment by Hooligan00** [comment]
Thank you I appreciate the help!
