### ISSUE TITLE
Ender Dragon '+15% damage per Difficulty' configurable

### ISSUE THREAD

**Issue by SextupleTap** [Insane96/ProgressiveBosses#35]
It would be nice to also have the Ender Dragons buff of +15% damage per difficulty to be configurable, since everything else is completely configurable having this feature configurable too would be beneficial.

**Comment by Insane96** [comment]
1.12 or 1.14?
Still it totally passed off my mind. Will surely do.

**Comment by SextupleTap** [comment]
I made this whilst using the 1.12 version, thanks for the swift response as well!
