### ISSUE TITLE
[MC1.14] Server freeze on World#getEntitiesWithinAABB() in Dragon.setStats()

### ISSUE THREAD

**Issue by ProsperCraft** [Insane96/ProgressiveBosses#37]
ProgressiveBosses-2.1.0.jar

forge-1.14.4-28.0.21

Dedicated server -

Warmroast below.
![b8a7ee7ad2938e9bacbf76bf9e54a155](https://user-images.githubusercontent.com/4427684/62014983-c0bd7b00-b164-11e9-9ff2-5d06efbc24d6.png)

When a player teleported to the end.

Once Progressive bosses was removed, he went again to the end, no lockup.

**Comment by Insane96** [comment]
You mean the server froze?

**Comment by Insane96** [comment]
Could you try to summon a Wither and tell me if still freezes the server?

**Comment by ProsperCraft** [comment]
This does not happen in single player, and it does not happen with a wither.

**Comment by Insane96** [comment]
Ok thanks. I will investigate

**Comment by Insane96** [comment]
Could you try with newer Forge version?

**Comment by ProsperCraft** [comment]
Fortunately, I am aware of this and made a video about it ;) https://youtu.be/-uUr1VAnkcs

We  are on an update freeze while we are waiting for all of the mods to update to the new breaking forge changes, especiall JEI needs to update.

**Comment by Insane96** [comment]
I'm going to spam the video everywhere. Also I'm going to try to fix this
when it's confirmed to not be a bug from Forge

Il Mer 7 Ago 2019, 17:11 Goshen <notifications@github.com> ha scritto:

**Comment by Insane96** [comment]
Does this still happen with Forge 28.1?

**Comment by Insane96** [comment]
No more replies. Closing.
