### ISSUE TITLE
[MC1.14] Crash when command is registered on newer Forge versions

### ISSUE THREAD

**Issue by Sunekaer** [Insane96/ProgressiveBosses#38]
forge:28.0.45
ProgressiveBosses-2.1.0.jar 
https://s1.sunekaer.com/files/crash-2019-08-06_19.51.09-server.txt

**Comment by Insane96** [comment]
Does it crashes with older Forge Versions?

**Comment by Sunekaer** [comment]
worked with .38 havent tested others

**Comment by Insane96** [comment]
Also when it crashes?

**Comment by Insane96** [comment]
It should work with .41, for some reasons in the dev enviornment I get no problems with .45

Try updating the mod to 2.1.1

**Comment by Insane96** [comment]
Seems like I have no problems in 28.1.10 either client or server
