### ISSUE TITLE
You can add support for The Twilight Forest  boss？

### ISSUE THREAD

**Issue by Abo233** [Insane96/ProgressiveBosses#40]

**Comment by Insane96** [comment]
Nah, Twitlight forest bosses are already cool.

**Comment by Abo233** [comment]
Let the boss of the twilight forest become stronger and stronger

**Comment by Abo233** [comment]
When you add the Scaling Health mod,it is not hard to fight

**Comment by Abo233** [comment]
I think that  the boss should be killed every time ,the next time it will become stronger

**Comment by Abo233** [comment]
Increased aromor and health,attack power
Values can be modified by the player
