### ISSUE TITLE
spawning dragon by command causes crash

### ISSUE THREAD

**Issue by ghost** [Insane96/ProgressiveBosses#51]
ProgressiveBosses 2.1.4
Minecraft 1.14.4
Forge 28.2.1
Optifine: No

using this command causes a hard crash
/summon ender_dragon ~ ~1 ~ {DragonPhase:4,CustomName:"\"Puff\""}

CrashLog [https://pastebin.com/CudB415v](https://pastebin.com/CudB415v)
LatestLog [https://pastebin.com/srx9S51U](https://pastebin.com/srx9S51U)

**Comment by Insane96** [comment]
1.14 is no longer supported
