### ISSUE TITLE
Crash Server Ticking Entity [1.15.2]

### ISSUE THREAD

**Issue by epeeforteyt** [Insane96/ProgressiveBosses#53]
Hey, I had a server crash with the Dragon entity here is the crash report

Forge: forge-1.15.2-31.1.41.jar
Mods: ProgressiveBosses-2.1.4-mc1.15.2.jar

[crash-2020-04-10_01.43.28-server.txt](https://github.com/Insane96/ProgressiveBosses/files/4459133/crash-2020-04-10_01.43.28-server.txt)

I don't know if it was your mod that crashed, but I'm posting it here :)

sorry english is not my language

**Comment by Insane96** [comment]
Did you spawn the ender dragon with commands?

**Comment by Insane96** [comment]
Fixed via https://github.com/Insane96/ProgressiveBosses/commit/ef2471ae18512017f6d4ac7ede386536254f4b03
