### ISSUE TITLE
Increase Ender Dragon's acid pool damage along with the melee damage

### ISSUE THREAD

**Issue by Spinogaming** [Insane96/ProgressiveBosses#56]
Increase Ender Dragon's acid pool damage along with the melee damage

**Comment by Insane96** [comment]
A new config option will be added for this. My only concern is that the acid pool's damage is magic damage so (other than with Protection ench) there's no real way to protect yourself. I will do some testing.

**Comment by Spinogaming** [comment]
Perhaps if that is too overpowered, maybe the ender dragon could start firing more of them in a row?

**Comment by Insane96** [comment]
I mean, it will be configurable and I'll do tests to prevent it from begin OP after a few drakes.

**Comment by Insane96** [comment]
Closed via https://github.com/Insane96/ProgressiveBosses/commit/3eb4447bac54dbfbd78e119214c0faa875177fd0
