### ISSUE TITLE
If possible. Revert the ender dragon to pre 1.15 behaviour

### ISSUE THREAD

**Issue by Spinogaming** [Insane96/ProgressiveBosses#57]
Currently in 1.15, the ender dragon cannot make sharp downwards dives. Meaning that not only does she go back and forth to go to the end fountain, she also cannot charge directly at the player, only slightly above it. So if you aren't levitating by the shulkers, she can't really hit you

**Comment by Insane96** [comment]
This is a bug that I hate, this started happening in 1.13, I don't know what Mojang messed up but yeah, the dragon fight was already pretty easy, now it's even more simpler.
That said, there's no way to fix this other than rewriting the dragon AI, and that would take way too much time.
