### ISSUE TITLE
Server Crash - Valhelsia 2.2.6

### ISSUE THREAD

**Issue by MaddocksL** [Insane96/ProgressiveBosses#58]
Got a server crash when player was fighting Dragon and a Larva attacked them.

[crash-2020-08-03_21.20.53-server.txt](https://github.com/Insane96/ProgressiveBosses/files/5018776/crash-2020-08-03_21.20.53-server.txt)

Player in full botania armour (the green one, whatever that is) and enchanted.

**Comment by Insane96** [comment]
There is no error from Progressive bosses.
