### ISSUE TITLE
Ender dragon spawning whenever entering The End

### ISSUE THREAD

**Issue by Lingaaah** [Insane96/ProgressiveBosses#59]
Hey there, I'm currently playing Valhelsia 2 (2.2.7) and whenever I re-enter the end the dragon respawns. I have not made any end crystals to try and respawn the dragon, it just seems to be doing it passively. I'm not 100% sure if your mod is what's doing it/that's where the issues lies but I thought it would be a good start, thank you!

**Comment by Insane96** [comment]
Need more infos, can't reproduce

**Comment by Lingaaah** [comment]
The ender crystals do not respawn when re-entering the end, the portal to return back home is still there while fighting the repspawned dragon as well. I'm not quite sure what else there is to tell, but I'd be happy to send you the save file if that would help at all.

**Comment by Insane96** [comment]
How many mods do you have? Does it happen with Progressive Bosses only?
Also PB does nothing to the dragon/wither spawn so pretty sure isn't my mod.

**Comment by Lingaaah** [comment]
I believe the modpack has 175 mods, and I'm not quite sure, I haven't tested myself but I'll make an issue in the Valhesia Modpack github instead, thank you for your help though!
