### ISSUE TITLE
Kill counter resets on Server.

### ISSUE THREAD

**Issue by smallerYeet** [Insane96/ProgressiveBosses#67]
The kill counter for any boss killed on my Server resets. I don't know when, but I have defeated about 3 Withers and 5+ Dragons. 
https://imgur.com/a/RGTa5V8

I can provide log's etc if necessary

**Comment by Insane96** [comment]
When did this happen?

**Comment by smallerYeet** [comment]
I would guess every rejoin. 
The mod works, because when we do the Wither / Ender dragon, there are Minions's spawning etc. It just resets somehow.
https://github.com/Darkhax-Minecraft/Cursed/files/5650736/listmods.txt
here my modlist

**Comment by Insane96** [comment]
Did this happen again? I'm closing this for now

**Comment by cute-catgirl** [comment]
this is happening for me too

**Comment by Insane96** [comment]
With no new information I can't really do much.
Also does this happen with only progressive bosses?

**Comment by cute-catgirl** [comment]
No, I have other mods installed too, here's the list:
- Progressive Bosses
- Charm
- Create
- Immersive Portals
- Quark
- Quark Oddities
- FTB Backups
- FTB GUI Library
- JEI
(Plus all the libraries for the mods)

**Comment by Insane96** [comment]
You need to repro that with just Progressive Bosses (and InsaneLib if
you're using 3.0.0+)

Il Ven 25 Giu 2021, 21:56 Ben ***@***.***> ha scritto:
