### ISSUE TITLE
Mod does not support 1.16.5?

### ISSUE THREAD

**Issue by ModernGamingWorld** [Insane96/ProgressiveBosses#70]
Love this mod and was wondering will it be on 1.16.5

**Comment by Insane96** [comment]
If you install manually does it launch?

**Comment by ModernGamingWorld** [comment]
@Insane96 it does, but it wont sync across the api unless you add 1.16.5 support on the latest version

**Comment by Insane96** [comment]
I don't understand which support is needed

Il Mar 2 Feb 2021, 08:34 ModernGamingWorld <notifications@github.com> ha
scritto:

**Comment by Insane96** [comment]
I'm guessing you needed it updated on CurseForge
