### ISSUE TITLE
Wither Difficulty Changes on Summon Instead of Kill

### ISSUE THREAD

**Issue by Yuogusy** [Insane96/ProgressiveBosses#88]
It seems like you know this, as it is even phrased as such with the commands, but is it intended that the difficulty of the wither changes even if it isn't killed by the player, e.g. on summon and not on a kill?

I ask because in the pack I am playing, I've noticed that the wither occasionally seems to de-spawn if there is no mob/player within a certain range of it. I'm not sure if this is a feature of vanilla, your mod, or some other mod in the pack, but that isn't really the issue. The issue is that if a player summons a wither but can't kill it because it is too difficult, should the difficulty really be increased?

Please close this if I am misunderstanding how the mod is intended to work. Thanks!

**Comment by Insane96** [comment]
It's intended. But yeah, I questioned myself if this should be yhe opposite.
