### ISSUE TITLE
Botania's Pink Wither spawns minions

### ISSUE THREAD

**Issue by wilyank** [Insane96/ProgressiveBosses#89]
First of all, all of us on our server are loving your mod. It really adds to the bossfights that would otherwise be easy in end game.

We noticed a problem though: Progressive Bosses sees the pink wither from Botania (entity id is botania:pink_wither) as a normal wither and spawns minions around it. As the pink wither is supposed to be passive, I do no think this should be the case.

As a side note, if Tinker's Construct is used along with this bug/feature it makes for a great wither skull farm

**Comment by Insane96** [comment]
Thanks for your kind words.

Also yes I totally forgot to re-add the pink wither to the blacklist. I'll do it ASAP.

As for the Tinkers' farm, I would love if that wasn't intended, but they don't take into account the loot table of the mob when using the Beheading (now renamed, i don't remember the new name) modifier. Would be really cool if you could open an issue on TiCon issue tracker mentioning that.

Thanks for the report.

**Comment by wilyank** [comment]
About the Severing dropping wither skulls, I brought it up on the Tinker's discord. They argue it works as intended, as those minions are vanilla wither skeletons after all.

**Comment by Insane96** [comment]
Yep, read through the conversation. I will fix the Pink Wither anyway.

**Comment by Insane96** [comment]
Do Shulkers drop the shell when using the TiCon modifier?

**Comment by Insane96** [comment]
Also Wither Minions will be an actual entity and will drop nothing.
