### ISSUE TITLE
[Suggestion] Add barriers to the main end island when the dragon’s difficulty is at it’s starting difficulty (so by default, 0)

### ISSUE THREAD

**Issue by Neko2n** [Insane96/ProgressiveBosses#91]
My idea of how to keep players on the main end island and to disallow riding mounts or using really fast movement accessories to leave the dragon’s arena the first time you fight it would be 8 differently-colored end crystals that spawn around the main end island sort of like buoys. They'd form an octagon shape around the island, and there'd be crystal beams connecting the crystals. If you fly past the crystals before killing the ender dragon, the closest crystal to the player would shoot red and orange homing shulker bullets at you every 5 seconds or so that explode with the power of a block of primed tnt when they make contact with you. The crystals would be immune to being destroyed btw, and would only explode after the ender dragon finishes its death animation.
Because they’d only exist when the dragon’s difficulty is at its minimum, you’d only be unable to leave the main end island during the first time you fight the dragon.
Reason I’m suggesting this is because in many modpacks (namely, mine), you can escape the dragon fight using mounts like Iceandfire’s dragons. This feature would prevent that, and would therefore prevent datapack bugs and other issues that result from escaping the main end island and exploring the outer end. It would also prevent getting end-game gear before even fighting the dragon like the Elytra.

**Comment by Insane96** [comment]
No, I don't want to prevent the player from leaving the area, expecially because the first dragon is supposed to be the vanilla one.
