### ISSUE TITLE
Server crash after world loaded

### ISSUE THREAD

**Issue by frank89722** [Insane96/ProgressiveBosses#92]
Progressive bosses 3.2.0
Crash report: https://gist.github.com/frank89722/571a0719f484d0bcebad209de2edd3d8

After ProgressiveBosses was removed, the server can run normally.
Please let me know if this should report to CyclopsCore.

Thanks!

**Comment by Insane96** [comment]
There's a Wither in the server?

**Comment by frank89722** [comment]
Yes, some people on the server imprisoned wither

**Comment by Insane96** [comment]
Ok, pretty strange bug. Is the wither in the spawn chunks or always loaded chunks?

**Comment by frank89722** [comment]
They are not in the spawn chunks.
But they are inside FTB force-loaded chunk.  However, I have disabled the chunk force load when players got offline.

**Comment by Insane96** [comment]
But when someone comes back online the game loads the chunks?

**Comment by frank89722** [comment]
> But when someone comes back online the game loads the chunks?

Yes. But the crash is happed after the server load the world before anyone join.

I'm not sure if this information can help.
But I think I have some mods that could cause chunk load on server start.
And I have [dynamic view](https://github.com/ldtteam/DynView) mod installed which had a chunk unload delay feature.

**Comment by Insane96** [comment]
Yep, that's definitely the reason. Thanks for the infos.

For me: remove or add a range and null check for nearest player when wither / dragon enter the world.

**Comment by Insane96** [comment]
Please test the latest alpha version to see if the issue is solved.

**Comment by frank89722** [comment]
Sorry for the late response.
I have no issue with the latest release version, thank you :)
