### ISSUE TITLE
[MC 1.16.5] Issue when first enter of End.

### ISSUE THREAD

**Issue by Iskalldren** [Insane96/ProgressiveBosses#95]
Version of Progressive Bosses: 3.3.2
Minecraft Version: 1.16.5

Description:
When I first entered the end, I could load up on the spawn platform but once I attempted to fly towards the main End Island my game crashed.

Attached is my crash report:
[Uploading crash-2021-09-09_13.31.20-server.txt…]()

**Comment by Insane96** [comment]
Report an issue using the template ... nothing changes from discord if you just upload the crash log

**Comment by Iskalldren** [comment]
Mind if I ask where I could view the format, I'm kinda new to github.
