### ISSUE TITLE
Crash when Min Cooldowns are higher than Max Cooldowns

### ISSUE THREAD

**Issue by Iskalldren** [Insane96/ProgressiveBosses#96]
**Describe the bug**
When I first entered the End, I managed to spawn on the end spawn platform but once I began to move towards the main island, my game crashed. I am using a custom mod pack so it might be the reason for the crash but the crash report spat out progressive bosses so I assumed it might be from here.

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.4
 - Progressive Bosses: 3.3.2
 - InsaneLib: 1.2.1

**Steps to reproduce**
1. Load up into the end.
2. Fly towards the main Island
3. Crash Occurs.

**Expected behaviour**
The game shouldn't crash in the end.

**Logs**
Crash Report: 
[crash-2021-09-09_13.31.20-server.txt](https://github.com/Insane96/ProgressiveBosses/files/7133882/crash-2021-09-09_13.31.20-server.txt)

**Can the issue be reproduced with a minimal set of mods? (E.g. Progressive Bosses + InsaneLib + Tinkers' Construct)**
Have not tried.

**Comment by Insane96** [comment]
Did you change the config?

**Comment by Iskalldren** [comment]
Yup I did, wanted to make the dragon fight more difficult. Would You like me to upload the config file I changed?

**Comment by Insane96** [comment]
Still a bug, but you set min cooldown of minions higher than max cooldown

Il Gio 9 Set 2021, 08:25 Iskalldren ***@***.***> ha scritto:

**Comment by Iskalldren** [comment]
Ah okie so if I change that then it should fix itself?

**Comment by Insane96** [comment]
Yes. Gonna rename the issue.
